---
- name: check for backuppc ssh key
  local_action: stat path={{ playbook_dir }}/files/ssh_user_keys/backuppc
  register: backuppc_ssh_key_file
  become: no
- name: do backuppc setup
  block:
  - name: install backuppc ssh key for root
    authorized_key:
      user: root
      state: present
      exclusive: yes
      key: "{{ lookup('file', 'ssh_user_keys/backuppc') }}"
  - name: install rsync for backuppc for Debian
    apt:
      name: "rsync"
      update_cache: true
      cache_valid_time: 86400
      state: present
    when: ansible_os_family == 'Debian'
  - name: install rsync for backuppc for OpenBSD
    openbsd_pkg:
      name: rsync--
      state: present
    when: ansible_distribution == 'OpenBSD'
  when: backuppc_ssh_key_file.stat.exists
