---
- name: install tzdata for Debian
  apt:
    name: "tzdata"
    update_cache: true
    cache_valid_time: 86400
    state: present
  when: ansible_os_family == 'Debian'
- name: set timezone
  timezone:
    name: "{{ server_timezone }}"

